/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserStats {
    newUsersLast24h: bigint;
    newUsersLast30d: bigint;
    totalUsers: bigint;
    newUsersLast7d: bigint;
}
export interface AiChatRequest {
    messages: Array<AiChatMessage>;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface PaymentRecord {
    id: string;
    status: PaymentStatus;
    method: PaymentMethod;
    createdAt: bigint;
    user: Principal;
    updatedAt: bigint;
    proof?: PaymentProof;
    amount: bigint;
}
export interface Bookmark {
    createdAt: bigint;
    user: Principal;
    questionId: string;
}
export interface CsvPreview {
    validationResults: Array<ValidationResult>;
    rows: Array<Array<string>>;
    importMode?: ImportMode;
    headers: Array<string>;
    delimiter: string;
}
export interface CsvImportResult {
    errors: Array<string>;
    importedCount: bigint;
    message: string;
    success: boolean;
}
export interface AiAssistantConfig {
    lastUpdated: bigint;
    enabled: boolean;
    apiKey: string;
}
export interface PaymentConfiguration {
    localBankDetails?: string;
    updatedAt: bigint;
    stcPayBarcodePath?: string;
}
export interface PaymentProof {
    filePath: string;
    fileType: string;
    uploadedAt: bigint;
}
export interface BrandAssets {
    soundPath?: string;
    logoPath?: string;
    updatedAt: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface StudentProgress {
    streak: bigint;
    badges: Array<string>;
    totalAttempts: bigint;
    completedQuestions: bigint;
    correctAnswers: bigint;
    weakAreas: Array<string>;
    accuracy: number;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface FileReference {
    hash: string;
    path: string;
}
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface AiChatMessage {
    content: string;
    role: string;
}
export interface Comment {
    id: string;
    content: string;
    createdAt: bigint;
    user: Principal;
    approved: boolean;
    questionId: string;
}
export interface ModeStats {
    accuracyPercentage: number;
    timeSpent: bigint;
    questionsAttempted: bigint;
    sessionsCompleted: bigint;
    questionsCorrect: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface DomainTopic {
    id: string;
    name: string;
    createdAt: bigint;
    type: DomainTopicType;
    updatedAt: bigint;
}
export interface AggregateStats {
    totalTimeSpent: bigint;
    totalQuestionsAttempted: bigint;
    totalQuestionsCorrect: bigint;
    totalSessionsCompleted: bigint;
    overallAccuracy: number;
}
export interface ValidationResult {
    errors: Array<string>;
    rowIndex: bigint;
    isValid: boolean;
}
export interface Question {
    id: string;
    content: string;
    domain: string;
    explanation: string;
    createdAt: bigint;
    questionType: QuestionType;
    version: bigint;
    updatedAt: bigint;
    state: QuestionState;
    correctAnswers: Array<bigint>;
    options: Array<string>;
}
export interface StudyStatistics {
    aggregateStats: AggregateStats;
    reviewModeStats: ModeStats;
    timedModeStats: ModeStats;
    practiceModeStats: ModeStats;
}
export interface UserProfile {
    paymentStatus: PaymentStatus;
    name: string;
    paymentProof?: PaymentProof;
    registrationTime: bigint;
}
export interface UserActivity {
    user: Principal;
    loginCount: bigint;
    commentCount: bigint;
    lastLogin: bigint;
    questionAttempts: bigint;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum DomainTopicType {
    topic = "topic",
    domain = "domain"
}
export enum ImportMode {
    other = "other",
    users = "users",
    questions = "questions"
}
export enum PaymentMethod {
    localBank = "localBank",
    stcBank = "stcBank"
}
export enum PaymentStatus {
    active = "active",
    expired = "expired",
    pending = "pending"
}
export enum QuestionState {
    published = "published",
    draft = "draft",
    archived = "archived"
}
export enum QuestionType {
    multiSelect = "multiSelect",
    singleChoice = "singleChoice",
    numeric = "numeric",
    trueFalse = "trueFalse"
}
export enum StudyMode {
    review = "review",
    timed = "timed",
    practice = "practice"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addBookmark(questionId: string): Promise<void>;
    addComment(comment: Comment): Promise<void>;
    addDomainTopic(id: string, name: string, type: DomainTopicType): Promise<void>;
    addPaymentRecord(record: PaymentRecord): Promise<void>;
    addQuestion(question: Question): Promise<void>;
    approveComment(commentId: string): Promise<void>;
    approvePayment(paymentRecordId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelCsvPreview(previewId: string): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deepSeekChat(request: AiChatRequest): Promise<string>;
    deleteAiAssistantConfig(): Promise<void>;
    deleteComment(commentId: string): Promise<void>;
    deleteCsvPreview(previewId: string): Promise<void>;
    deleteDomainTopic(id: string): Promise<void>;
    deleteQuestion(questionId: string): Promise<void>;
    dropFileReference(path: string): Promise<void>;
    getAiAssistantConfig(): Promise<AiAssistantConfig | null>;
    getAllDomains(): Promise<Array<DomainTopic>>;
    getAllDomainsAndTopics(): Promise<Array<DomainTopic>>;
    getAllQuestions(): Promise<Array<Question>>;
    getAllUsers(): Promise<Array<[Principal, UserProfile]>>;
    getBookmarks(): Promise<Array<Bookmark>>;
    getBrandAssets(): Promise<BrandAssets | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComments(): Promise<Array<Comment>>;
    getCsvPreview(previewId: string): Promise<CsvPreview>;
    getCsvPreviewDelimiter(previewId: string): Promise<string>;
    getCsvPreviewHeaders(previewId: string): Promise<Array<string>>;
    getCsvPreviewRows(previewId: string): Promise<Array<Array<string>>>;
    getCsvPreviewValidationResults(previewId: string): Promise<Array<ValidationResult>>;
    getDomainTopics(): Promise<Array<DomainTopic>>;
    getDomains(): Promise<Array<DomainTopic>>;
    getFileReference(path: string): Promise<FileReference>;
    getOrphanQuestions(): Promise<Array<Question>>;
    getPaymentConfiguration(): Promise<PaymentConfiguration | null>;
    getPaymentRecords(): Promise<Array<PaymentRecord>>;
    getQuestions(): Promise<Array<Question>>;
    getQuestionsByFilter(domain: string | null, difficulty: string | null): Promise<Array<Question>>;
    getQuestionsByMode(mode: StudyMode): Promise<Array<Question>>;
    getQuestionsWithDomains(): Promise<Array<Question>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getStudentProgress(): Promise<StudentProgress | null>;
    getStudyStatistics(): Promise<StudyStatistics | null>;
    getUserActivities(): Promise<Array<UserActivity>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserStats(): Promise<UserStats>;
    initializeAccessControl(): Promise<void>;
    initializeDomains(): Promise<void>;
    isAiAssistantEnabled(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listFileReferences(): Promise<Array<FileReference>>;
    processCsvPreview(previewId: string): Promise<CsvImportResult>;
    registerFileReference(path: string, hash: string): Promise<void>;
    removeBookmark(questionId: string): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCsvPreview(previewId: string, preview: CsvPreview): Promise<void>;
    saveStudentProgress(progress: StudentProgress): Promise<void>;
    saveStudyStatistics(stats: StudyStatistics): Promise<void>;
    searchQuestions(searchTerm: string): Promise<Array<Question>>;
    setAiAssistantConfig(apiKey: string, enabled: boolean): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBrandAssets(logoPath: string | null, soundPath: string | null): Promise<void>;
    updateCsvPreviewDelimiter(previewId: string, newDelimiter: string): Promise<void>;
    updateCsvPreviewHeaders(previewId: string, newHeaders: Array<string>): Promise<void>;
    updateCsvPreviewImportMode(previewId: string, newImportMode: ImportMode | null): Promise<void>;
    updateCsvPreviewRows(previewId: string, newRows: Array<Array<string>>): Promise<void>;
    updateCsvPreviewValidationResults(previewId: string, newValidationResults: Array<ValidationResult>): Promise<void>;
    updateDomainTopic(id: string, newName: string): Promise<void>;
    updatePaymentConfiguration(stcPayBarcodePath: string | null, localBankDetails: string | null): Promise<void>;
    updatePaymentRecord(record: PaymentRecord): Promise<void>;
    updateQuestion(question: Question): Promise<void>;
    updateUserActivity(loginCount: bigint, questionAttempts: bigint, commentCount: bigint, lastLogin: bigint): Promise<void>;
    uploadPaymentProof(paymentRecordId: string, filePath: string, fileType: string): Promise<void>;
    validateCsvPreviewDelimiter(previewId: string): Promise<boolean>;
}
import type { AiAssistantConfig as _AiAssistantConfig, ApprovalStatus as _ApprovalStatus, BrandAssets as _BrandAssets, CsvPreview as _CsvPreview, DomainTopic as _DomainTopic, DomainTopicType as _DomainTopicType, ImportMode as _ImportMode, PaymentConfiguration as _PaymentConfiguration, PaymentMethod as _PaymentMethod, PaymentProof as _PaymentProof, PaymentRecord as _PaymentRecord, PaymentStatus as _PaymentStatus, Question as _Question, QuestionState as _QuestionState, QuestionType as _QuestionType, StripeSessionStatus as _StripeSessionStatus, StudentProgress as _StudentProgress, StudyMode as _StudyMode, StudyStatistics as _StudyStatistics, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, ValidationResult as _ValidationResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBookmark(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBookmark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBookmark(arg0);
            return result;
        }
    }
    async addComment(arg0: Comment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0);
            return result;
        }
    }
    async addDomainTopic(arg0: string, arg1: string, arg2: DomainTopicType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDomainTopic(arg0, arg1, to_candid_DomainTopicType_n1(this.uploadFile, this.downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDomainTopic(arg0, arg1, to_candid_DomainTopicType_n1(this.uploadFile, this.downloadFile, arg2));
            return result;
        }
    }
    async addPaymentRecord(arg0: PaymentRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPaymentRecord(to_candid_PaymentRecord_n3(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPaymentRecord(to_candid_PaymentRecord_n3(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async addQuestion(arg0: Question): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(to_candid_Question_n9(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(to_candid_Question_n9(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async approveComment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveComment(arg0);
            return result;
        }
    }
    async approvePayment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePayment(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async cancelCsvPreview(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelCsvPreview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelCsvPreview(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deepSeekChat(arg0: AiChatRequest): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.deepSeekChat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deepSeekChat(arg0);
            return result;
        }
    }
    async deleteAiAssistantConfig(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAiAssistantConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAiAssistantConfig();
            return result;
        }
    }
    async deleteComment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteCsvPreview(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCsvPreview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCsvPreview(arg0);
            return result;
        }
    }
    async deleteDomainTopic(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDomainTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDomainTopic(arg0);
            return result;
        }
    }
    async deleteQuestion(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuestion(arg0);
            return result;
        }
    }
    async dropFileReference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dropFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dropFileReference(arg0);
            return result;
        }
    }
    async getAiAssistantConfig(): Promise<AiAssistantConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAiAssistantConfig();
                return from_candid_opt_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAiAssistantConfig();
            return from_candid_opt_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllDomains(): Promise<Array<DomainTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDomains();
                return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDomains();
            return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllDomainsAndTopics(): Promise<Array<DomainTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDomainsAndTopics();
                return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDomainsAndTopics();
            return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllQuestions(): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuestions();
                return from_candid_vec_n23(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuestions();
            return from_candid_vec_n23(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n30(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n30(this.uploadFile, this.downloadFile, result);
        }
    }
    async getBookmarks(): Promise<Array<Bookmark>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookmarks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookmarks();
            return result;
        }
    }
    async getBrandAssets(): Promise<BrandAssets | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBrandAssets();
                return from_candid_opt_n37(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBrandAssets();
            return from_candid_opt_n37(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n41(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n41(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n42(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n42(this.uploadFile, this.downloadFile, result);
        }
    }
    async getComments(): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments();
            return result;
        }
    }
    async getCsvPreview(arg0: string): Promise<CsvPreview> {
        if (this.processError) {
            try {
                const result = await this.actor.getCsvPreview(arg0);
                return from_candid_CsvPreview_n44(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCsvPreview(arg0);
            return from_candid_CsvPreview_n44(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCsvPreviewDelimiter(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCsvPreviewDelimiter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCsvPreviewDelimiter(arg0);
            return result;
        }
    }
    async getCsvPreviewHeaders(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCsvPreviewHeaders(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCsvPreviewHeaders(arg0);
            return result;
        }
    }
    async getCsvPreviewRows(arg0: string): Promise<Array<Array<string>>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCsvPreviewRows(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCsvPreviewRows(arg0);
            return result;
        }
    }
    async getCsvPreviewValidationResults(arg0: string): Promise<Array<ValidationResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCsvPreviewValidationResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCsvPreviewValidationResults(arg0);
            return result;
        }
    }
    async getDomainTopics(): Promise<Array<DomainTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDomainTopics();
                return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDomainTopics();
            return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getDomains(): Promise<Array<DomainTopic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDomains();
                return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDomains();
            return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFileReference(arg0: string): Promise<FileReference> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileReference(arg0);
            return result;
        }
    }
    async getOrphanQuestions(): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrphanQuestions();
                return from_candid_vec_n23(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrphanQuestions();
            return from_candid_vec_n23(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPaymentConfiguration(): Promise<PaymentConfiguration | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentConfiguration();
                return from_candid_opt_n49(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentConfiguration();
            return from_candid_opt_n49(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPaymentRecords(): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentRecords();
                return from_candid_vec_n52(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentRecords();
            return from_candid_vec_n52(this.uploadFile, this.downloadFile, result);
        }
    }
    async getQuestions(): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestions();
                return from_candid_vec_n23(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestions();
            return from_candid_vec_n23(this.uploadFile, this.downloadFile, result);
        }
    }
    async getQuestionsByFilter(arg0: string | null, arg1: string | null): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsByFilter(to_candid_opt_n57(this.uploadFile, this.downloadFile, arg0), to_candid_opt_n57(this.uploadFile, this.downloadFile, arg1));
                return from_candid_vec_n23(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsByFilter(to_candid_opt_n57(this.uploadFile, this.downloadFile, arg0), to_candid_opt_n57(this.uploadFile, this.downloadFile, arg1));
            return from_candid_vec_n23(this.uploadFile, this.downloadFile, result);
        }
    }
    async getQuestionsByMode(arg0: StudyMode): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsByMode(to_candid_StudyMode_n58(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n23(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsByMode(to_candid_StudyMode_n58(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n23(this.uploadFile, this.downloadFile, result);
        }
    }
    async getQuestionsWithDomains(): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsWithDomains();
                return from_candid_vec_n23(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsWithDomains();
            return from_candid_vec_n23(this.uploadFile, this.downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n60(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n60(this.uploadFile, this.downloadFile, result);
        }
    }
    async getStudentProgress(): Promise<StudentProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentProgress();
                return from_candid_opt_n63(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentProgress();
            return from_candid_opt_n63(this.uploadFile, this.downloadFile, result);
        }
    }
    async getStudyStatistics(): Promise<StudyStatistics | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudyStatistics();
                return from_candid_opt_n64(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudyStatistics();
            return from_candid_opt_n64(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserActivities(): Promise<Array<UserActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserActivities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserActivities();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n41(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n41(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserStats(): Promise<UserStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStats();
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async initializeDomains(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeDomains();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeDomains();
            return result;
        }
    }
    async isAiAssistantEnabled(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAiAssistantEnabled();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAiAssistantEnabled();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n65(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n65(this.uploadFile, this.downloadFile, result);
        }
    }
    async listFileReferences(): Promise<Array<FileReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFileReferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFileReferences();
            return result;
        }
    }
    async processCsvPreview(arg0: string): Promise<CsvImportResult> {
        if (this.processError) {
            try {
                const result = await this.actor.processCsvPreview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processCsvPreview(arg0);
            return result;
        }
    }
    async registerFileReference(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFileReference(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFileReference(arg0, arg1);
            return result;
        }
    }
    async removeBookmark(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBookmark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBookmark(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n70(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n70(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async saveCsvPreview(arg0: string, arg1: CsvPreview): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCsvPreview(arg0, to_candid_CsvPreview_n72(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCsvPreview(arg0, to_candid_CsvPreview_n72(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async saveStudentProgress(arg0: StudentProgress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStudentProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStudentProgress(arg0);
            return result;
        }
    }
    async saveStudyStatistics(arg0: StudyStatistics): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStudyStatistics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStudyStatistics(arg0);
            return result;
        }
    }
    async searchQuestions(arg0: string): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchQuestions(arg0);
                return from_candid_vec_n23(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchQuestions(arg0);
            return from_candid_vec_n23(this.uploadFile, this.downloadFile, result);
        }
    }
    async setAiAssistantConfig(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAiAssistantConfig(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAiAssistantConfig(arg0, arg1);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n76(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n76(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBrandAssets(arg0: string | null, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBrandAssets(to_candid_opt_n57(this.uploadFile, this.downloadFile, arg0), to_candid_opt_n57(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBrandAssets(to_candid_opt_n57(this.uploadFile, this.downloadFile, arg0), to_candid_opt_n57(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async updateCsvPreviewDelimiter(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCsvPreviewDelimiter(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCsvPreviewDelimiter(arg0, arg1);
            return result;
        }
    }
    async updateCsvPreviewHeaders(arg0: string, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCsvPreviewHeaders(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCsvPreviewHeaders(arg0, arg1);
            return result;
        }
    }
    async updateCsvPreviewImportMode(arg0: string, arg1: ImportMode | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCsvPreviewImportMode(arg0, to_candid_opt_n78(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCsvPreviewImportMode(arg0, to_candid_opt_n78(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async updateCsvPreviewRows(arg0: string, arg1: Array<Array<string>>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCsvPreviewRows(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCsvPreviewRows(arg0, arg1);
            return result;
        }
    }
    async updateCsvPreviewValidationResults(arg0: string, arg1: Array<ValidationResult>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCsvPreviewValidationResults(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCsvPreviewValidationResults(arg0, arg1);
            return result;
        }
    }
    async updateDomainTopic(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDomainTopic(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDomainTopic(arg0, arg1);
            return result;
        }
    }
    async updatePaymentConfiguration(arg0: string | null, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentConfiguration(to_candid_opt_n57(this.uploadFile, this.downloadFile, arg0), to_candid_opt_n57(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentConfiguration(to_candid_opt_n57(this.uploadFile, this.downloadFile, arg0), to_candid_opt_n57(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async updatePaymentRecord(arg0: PaymentRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentRecord(to_candid_PaymentRecord_n3(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentRecord(to_candid_PaymentRecord_n3(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async updateQuestion(arg0: Question): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuestion(to_candid_Question_n9(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuestion(to_candid_Question_n9(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async updateUserActivity(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserActivity(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserActivity(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async uploadPaymentProof(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPaymentProof(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPaymentProof(arg0, arg1, arg2);
            return result;
        }
    }
    async validateCsvPreviewDelimiter(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateCsvPreviewDelimiter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateCsvPreviewDelimiter(arg0);
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n68(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n69(uploadFile, downloadFile, value);
}
function from_candid_BrandAssets_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BrandAssets): BrandAssets {
    return from_candid_record_n39(uploadFile, downloadFile, value);
}
function from_candid_CsvPreview_n44(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CsvPreview): CsvPreview {
    return from_candid_record_n45(uploadFile, downloadFile, value);
}
function from_candid_DomainTopicType_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DomainTopicType): DomainTopicType {
    return from_candid_variant_n22(uploadFile, downloadFile, value);
}
function from_candid_DomainTopic_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DomainTopic): DomainTopic {
    return from_candid_record_n20(uploadFile, downloadFile, value);
}
function from_candid_ImportMode_n47(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImportMode): ImportMode {
    return from_candid_variant_n48(uploadFile, downloadFile, value);
}
function from_candid_PaymentConfiguration_n50(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentConfiguration): PaymentConfiguration {
    return from_candid_record_n51(uploadFile, downloadFile, value);
}
function from_candid_PaymentMethod_n55(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n56(uploadFile, downloadFile, value);
}
function from_candid_PaymentRecord_n53(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRecord): PaymentRecord {
    return from_candid_record_n54(uploadFile, downloadFile, value);
}
function from_candid_PaymentStatus_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n35(uploadFile, downloadFile, value);
}
function from_candid_QuestionState_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionState): QuestionState {
    return from_candid_variant_n29(uploadFile, downloadFile, value);
}
function from_candid_QuestionType_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionType): QuestionType {
    return from_candid_variant_n27(uploadFile, downloadFile, value);
}
function from_candid_Question_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n25(uploadFile, downloadFile, value);
}
function from_candid_StripeSessionStatus_n60(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n61(uploadFile, downloadFile, value);
}
function from_candid_UserApprovalInfo_n66(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n67(uploadFile, downloadFile, value);
}
function from_candid_UserProfile_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n33(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n42(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n43(uploadFile, downloadFile, value);
}
function from_candid_opt_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AiAssistantConfig]): AiAssistantConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentProof]): PaymentProof | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BrandAssets]): BrandAssets | null {
    return value.length === 0 ? null : from_candid_BrandAssets_n38(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n32(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n46(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ImportMode]): ImportMode | null {
    return value.length === 0 ? null : from_candid_ImportMode_n47(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n49(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentConfiguration]): PaymentConfiguration | null {
    return value.length === 0 ? null : from_candid_PaymentConfiguration_n50(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n63(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentProgress]): StudentProgress | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n64(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudyStatistics]): StudyStatistics | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: bigint;
    type: _DomainTopicType;
    updatedAt: bigint;
}): {
    id: string;
    name: string;
    createdAt: bigint;
    type: DomainTopicType;
    updatedAt: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        type: from_candid_DomainTopicType_n21(uploadFile, downloadFile, value.type),
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    domain: string;
    explanation: string;
    createdAt: bigint;
    questionType: _QuestionType;
    version: bigint;
    updatedAt: bigint;
    state: _QuestionState;
    correctAnswers: Array<bigint>;
    options: Array<string>;
}): {
    id: string;
    content: string;
    domain: string;
    explanation: string;
    createdAt: bigint;
    questionType: QuestionType;
    version: bigint;
    updatedAt: bigint;
    state: QuestionState;
    correctAnswers: Array<bigint>;
    options: Array<string>;
} {
    return {
        id: value.id,
        content: value.content,
        domain: value.domain,
        explanation: value.explanation,
        createdAt: value.createdAt,
        questionType: from_candid_QuestionType_n26(uploadFile, downloadFile, value.questionType),
        version: value.version,
        updatedAt: value.updatedAt,
        state: from_candid_QuestionState_n28(uploadFile, downloadFile, value.state),
        correctAnswers: value.correctAnswers,
        options: value.options
    };
}
function from_candid_record_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentStatus: _PaymentStatus;
    name: string;
    paymentProof: [] | [_PaymentProof];
    registrationTime: bigint;
}): {
    paymentStatus: PaymentStatus;
    name: string;
    paymentProof?: PaymentProof;
    registrationTime: bigint;
} {
    return {
        paymentStatus: from_candid_PaymentStatus_n34(uploadFile, downloadFile, value.paymentStatus),
        name: value.name,
        paymentProof: record_opt_to_undefined(from_candid_opt_n36(uploadFile, downloadFile, value.paymentProof)),
        registrationTime: value.registrationTime
    };
}
function from_candid_record_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    soundPath: [] | [string];
    logoPath: [] | [string];
    updatedAt: bigint;
}): {
    soundPath?: string;
    logoPath?: string;
    updatedAt: bigint;
} {
    return {
        soundPath: record_opt_to_undefined(from_candid_opt_n40(uploadFile, downloadFile, value.soundPath)),
        logoPath: record_opt_to_undefined(from_candid_opt_n40(uploadFile, downloadFile, value.logoPath)),
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n45(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    validationResults: Array<_ValidationResult>;
    rows: Array<Array<string>>;
    importMode: [] | [_ImportMode];
    headers: Array<string>;
    delimiter: string;
}): {
    validationResults: Array<ValidationResult>;
    rows: Array<Array<string>>;
    importMode?: ImportMode;
    headers: Array<string>;
    delimiter: string;
} {
    return {
        validationResults: value.validationResults,
        rows: value.rows,
        importMode: record_opt_to_undefined(from_candid_opt_n46(uploadFile, downloadFile, value.importMode)),
        headers: value.headers,
        delimiter: value.delimiter
    };
}
function from_candid_record_n51(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    localBankDetails: [] | [string];
    updatedAt: bigint;
    stcPayBarcodePath: [] | [string];
}): {
    localBankDetails?: string;
    updatedAt: bigint;
    stcPayBarcodePath?: string;
} {
    return {
        localBankDetails: record_opt_to_undefined(from_candid_opt_n40(uploadFile, downloadFile, value.localBankDetails)),
        updatedAt: value.updatedAt,
        stcPayBarcodePath: record_opt_to_undefined(from_candid_opt_n40(uploadFile, downloadFile, value.stcPayBarcodePath))
    };
}
function from_candid_record_n54(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _PaymentStatus;
    method: _PaymentMethod;
    createdAt: bigint;
    user: Principal;
    updatedAt: bigint;
    proof: [] | [_PaymentProof];
    amount: bigint;
}): {
    id: string;
    status: PaymentStatus;
    method: PaymentMethod;
    createdAt: bigint;
    user: Principal;
    updatedAt: bigint;
    proof?: PaymentProof;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n34(uploadFile, downloadFile, value.status),
        method: from_candid_PaymentMethod_n55(uploadFile, downloadFile, value.method),
        createdAt: value.createdAt,
        user: value.user,
        updatedAt: value.updatedAt,
        proof: record_opt_to_undefined(from_candid_opt_n36(uploadFile, downloadFile, value.proof)),
        amount: value.amount
    };
}
function from_candid_record_n62(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n40(uploadFile, downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n67(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n68(uploadFile, downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_tuple_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n32(uploadFile, downloadFile, value[1])
    ];
}
function from_candid_variant_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topic: null;
} | {
    domain: null;
}): DomainTopicType {
    return "topic" in value ? DomainTopicType.topic : "domain" in value ? DomainTopicType.domain : value;
}
function from_candid_variant_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    multiSelect: null;
} | {
    singleChoice: null;
} | {
    numeric: null;
} | {
    trueFalse: null;
}): QuestionType {
    return "multiSelect" in value ? QuestionType.multiSelect : "singleChoice" in value ? QuestionType.singleChoice : "numeric" in value ? QuestionType.numeric : "trueFalse" in value ? QuestionType.trueFalse : value;
}
function from_candid_variant_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    draft: null;
} | {
    archived: null;
}): QuestionState {
    return "published" in value ? QuestionState.published : "draft" in value ? QuestionState.draft : "archived" in value ? QuestionState.archived : value;
}
function from_candid_variant_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    expired: null;
} | {
    pending: null;
}): PaymentStatus {
    return "active" in value ? PaymentStatus.active : "expired" in value ? PaymentStatus.expired : "pending" in value ? PaymentStatus.pending : value;
}
function from_candid_variant_n43(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n48(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    users: null;
} | {
    questions: null;
}): ImportMode {
    return "other" in value ? ImportMode.other : "users" in value ? ImportMode.users : "questions" in value ? ImportMode.questions : value;
}
function from_candid_variant_n56(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    localBank: null;
} | {
    stcBank: null;
}): PaymentMethod {
    return "localBank" in value ? PaymentMethod.localBank : "stcBank" in value ? PaymentMethod.stcBank : value;
}
function from_candid_variant_n61(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n62(uploadFile, downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n69(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DomainTopic>): Array<DomainTopic> {
    return value.map((x)=>from_candid_DomainTopic_n19(uploadFile, downloadFile, x));
}
function from_candid_vec_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n24(uploadFile, downloadFile, x));
}
function from_candid_vec_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n31(uploadFile, downloadFile, x));
}
function from_candid_vec_n52(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentRecord>): Array<PaymentRecord> {
    return value.map((x)=>from_candid_PaymentRecord_n53(uploadFile, downloadFile, x));
}
function from_candid_vec_n65(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n66(uploadFile, downloadFile, x));
}
function to_candid_ApprovalStatus_n76(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n77(uploadFile, downloadFile, value);
}
function to_candid_CsvPreview_n72(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CsvPreview): _CsvPreview {
    return to_candid_record_n73(uploadFile, downloadFile, value);
}
function to_candid_DomainTopicType_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DomainTopicType): _DomainTopicType {
    return to_candid_variant_n2(uploadFile, downloadFile, value);
}
function to_candid_ImportMode_n74(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImportMode): _ImportMode {
    return to_candid_variant_n75(uploadFile, downloadFile, value);
}
function to_candid_PaymentMethod_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n8(uploadFile, downloadFile, value);
}
function to_candid_PaymentRecord_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentRecord): _PaymentRecord {
    return to_candid_record_n4(uploadFile, downloadFile, value);
}
function to_candid_PaymentStatus_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n6(uploadFile, downloadFile, value);
}
function to_candid_QuestionState_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionState): _QuestionState {
    return to_candid_variant_n14(uploadFile, downloadFile, value);
}
function to_candid_QuestionType_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): _QuestionType {
    return to_candid_variant_n12(uploadFile, downloadFile, value);
}
function to_candid_Question_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Question): _Question {
    return to_candid_record_n10(uploadFile, downloadFile, value);
}
function to_candid_StudyMode_n58(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudyMode): _StudyMode {
    return to_candid_variant_n59(uploadFile, downloadFile, value);
}
function to_candid_UserProfile_n70(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n71(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(uploadFile, downloadFile, value);
}
function to_candid_opt_n57(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n78(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImportMode | null): [] | [_ImportMode] {
    return value === null ? candid_none() : candid_some(to_candid_ImportMode_n74(uploadFile, downloadFile, value));
}
function to_candid_record_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    domain: string;
    explanation: string;
    createdAt: bigint;
    questionType: QuestionType;
    version: bigint;
    updatedAt: bigint;
    state: QuestionState;
    correctAnswers: Array<bigint>;
    options: Array<string>;
}): {
    id: string;
    content: string;
    domain: string;
    explanation: string;
    createdAt: bigint;
    questionType: _QuestionType;
    version: bigint;
    updatedAt: bigint;
    state: _QuestionState;
    correctAnswers: Array<bigint>;
    options: Array<string>;
} {
    return {
        id: value.id,
        content: value.content,
        domain: value.domain,
        explanation: value.explanation,
        createdAt: value.createdAt,
        questionType: to_candid_QuestionType_n11(uploadFile, downloadFile, value.questionType),
        version: value.version,
        updatedAt: value.updatedAt,
        state: to_candid_QuestionState_n13(uploadFile, downloadFile, value.state),
        correctAnswers: value.correctAnswers,
        options: value.options
    };
}
function to_candid_record_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: PaymentStatus;
    method: PaymentMethod;
    createdAt: bigint;
    user: Principal;
    updatedAt: bigint;
    proof?: PaymentProof;
    amount: bigint;
}): {
    id: string;
    status: _PaymentStatus;
    method: _PaymentMethod;
    createdAt: bigint;
    user: Principal;
    updatedAt: bigint;
    proof: [] | [_PaymentProof];
    amount: bigint;
} {
    return {
        id: value.id,
        status: to_candid_PaymentStatus_n5(uploadFile, downloadFile, value.status),
        method: to_candid_PaymentMethod_n7(uploadFile, downloadFile, value.method),
        createdAt: value.createdAt,
        user: value.user,
        updatedAt: value.updatedAt,
        proof: value.proof ? candid_some(value.proof) : candid_none(),
        amount: value.amount
    };
}
function to_candid_record_n71(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentStatus: PaymentStatus;
    name: string;
    paymentProof?: PaymentProof;
    registrationTime: bigint;
}): {
    paymentStatus: _PaymentStatus;
    name: string;
    paymentProof: [] | [_PaymentProof];
    registrationTime: bigint;
} {
    return {
        paymentStatus: to_candid_PaymentStatus_n5(uploadFile, downloadFile, value.paymentStatus),
        name: value.name,
        paymentProof: value.paymentProof ? candid_some(value.paymentProof) : candid_none(),
        registrationTime: value.registrationTime
    };
}
function to_candid_record_n73(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    validationResults: Array<ValidationResult>;
    rows: Array<Array<string>>;
    importMode?: ImportMode;
    headers: Array<string>;
    delimiter: string;
}): {
    validationResults: Array<_ValidationResult>;
    rows: Array<Array<string>>;
    importMode: [] | [_ImportMode];
    headers: Array<string>;
    delimiter: string;
} {
    return {
        validationResults: value.validationResults,
        rows: value.rows,
        importMode: value.importMode ? candid_some(to_candid_ImportMode_n74(uploadFile, downloadFile, value.importMode)) : candid_none(),
        headers: value.headers,
        delimiter: value.delimiter
    };
}
function to_candid_variant_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): {
    multiSelect: null;
} | {
    singleChoice: null;
} | {
    numeric: null;
} | {
    trueFalse: null;
} {
    return value == QuestionType.multiSelect ? {
        multiSelect: null
    } : value == QuestionType.singleChoice ? {
        singleChoice: null
    } : value == QuestionType.numeric ? {
        numeric: null
    } : value == QuestionType.trueFalse ? {
        trueFalse: null
    } : value;
}
function to_candid_variant_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionState): {
    published: null;
} | {
    draft: null;
} | {
    archived: null;
} {
    return value == QuestionState.published ? {
        published: null
    } : value == QuestionState.draft ? {
        draft: null
    } : value == QuestionState.archived ? {
        archived: null
    } : value;
}
function to_candid_variant_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DomainTopicType): {
    topic: null;
} | {
    domain: null;
} {
    return value == DomainTopicType.topic ? {
        topic: null
    } : value == DomainTopicType.domain ? {
        domain: null
    } : value;
}
function to_candid_variant_n59(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudyMode): {
    review: null;
} | {
    timed: null;
} | {
    practice: null;
} {
    return value == StudyMode.review ? {
        review: null
    } : value == StudyMode.timed ? {
        timed: null
    } : value == StudyMode.practice ? {
        practice: null
    } : value;
}
function to_candid_variant_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    active: null;
} | {
    expired: null;
} | {
    pending: null;
} {
    return value == PaymentStatus.active ? {
        active: null
    } : value == PaymentStatus.expired ? {
        expired: null
    } : value == PaymentStatus.pending ? {
        pending: null
    } : value;
}
function to_candid_variant_n75(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImportMode): {
    other: null;
} | {
    users: null;
} | {
    questions: null;
} {
    return value == ImportMode.other ? {
        other: null
    } : value == ImportMode.users ? {
        users: null
    } : value == ImportMode.questions ? {
        questions: null
    } : value;
}
function to_candid_variant_n77(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    localBank: null;
} | {
    stcBank: null;
} {
    return value == PaymentMethod.localBank ? {
        localBank: null
    } : value == PaymentMethod.stcBank ? {
        stcBank: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
